version: '2'
services:
    server:
        build:
            context: ./server
        ports:
        - "5000:5000"
    nginx:
        build:
            context: ./nginx
        ports:
        - "4080:80"
        - "4443:443"
        links:
        - server